name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: actions/cache/save@v3
      id: cache
      with:
        path: NESseract.Core/bin/Debug/net6.0
        key: build-${{ github.run_id }}
        
  package:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: NESseract.Core/bin/Debug/net6.0
          key: build-${{ github.run_id }}
      - name: Copy cache
        run: |
          mkdir Build
          cp NESseract.Core/bin/Debug/net6.0/* Build
      - uses: actions/upload-artifact@v3
        with:
          name: build-final
          path: Build
